---
title: "`readthedown` template example"
date: "`r Sys.Date()`"
author: juba
output:
  rmdformats::readthedown:
    self_contained: true
    thumbnails: false
    lightbox: false
---


```{r knitr_init, echo=FALSE, results="asis", cache=FALSE}
library(knitr)
library(rmdformats)
library(DT)
library(ggplot2)
## Global options
options(max.print = "75")
opts_chunk$set(echo = FALSE,
	             cache = FALSE,
               prompt = FALSE,
               tidy = FALSE,
               comment = NA,
               message = FALSE,
               warning = FALSE)
opts_knit$set(width = 75)
```

# 本講義の目標

- ポジティブ心理学の諸概念を、アクセプタンス&コミットメントセラピーの理論体系に基づいて、行動論的観点から理解し、臨床心理学的問題への介入方法に関する知識を習得する。

# 講義概要

- 本講読においては、ウェルビーイングの向上との関連が指摘されているポジティブ心理学の諸概念を、アクセプタンス&コミットメントセラピーの理論体系に基づいて行動論的観点から理解するための書籍を講読する。

# Mathjax

An incredibly complex equation :

$$ y = \sqrt{\frac{1}{x}} $$


# Figures

Here is an histogram.

```{r iris_hist}
ggplot(data=iris) +
    geom_histogram(aes(x=Petal.Width)) +
    facet_grid(Species~.)

```

And a wonderful scatterplot, with a caption.

```{r iris_scatter1, fig.cap="This is a caption"}
ggplot(data=iris) + geom_point(aes(x=Petal.Width, y=Petal.Length, color=Species))
```


